import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {initializeAuth,inMemoryPersistence,browserPopupRedirectResolver,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,query,where,orderBy,Timestamp,onSnapshot} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=initializeApp(firebaseConfig,'usage-report-admin');
const auth=initializeAuth(app,{persistence:inMemoryPersistence,popupRedirectResolver:browserPopupRedirectResolver});
const db=getFirestore(app);
const el=id=>document.getElementById(id);
let stop=null,records=[],authorized=false;
const columns=['occurredAt','employeeNumber','documentNumber','ip','ipStatus','action','result','errorCode','visitorId','sessionId','authUid'];
const titles=['時間','職號','文號','完整 IP','IP 狀態','功能','結果','錯誤類型','訪客代碼','工作階段','UID'];
function clearReport(){authorized=false;records=[];if(stop)stop();stop=null;el('report-content').hidden=true;el('metrics').textContent='';['employee-table','daily-table','record-table'].forEach(id=>el(id).replaceChildren());}
function message(text){el('message').textContent=text;}
function table(target,keys,labels,rows){const t=document.createElement('table'),head=document.createElement('thead'),hr=document.createElement('tr');labels.forEach(label=>{const c=document.createElement('th');c.textContent=label;hr.appendChild(c)});head.appendChild(hr);t.appendChild(head);const body=document.createElement('tbody');rows.forEach(row=>{const r=document.createElement('tr');keys.forEach(key=>{const c=document.createElement('td');c.textContent=row[key]??'';r.appendChild(c)});body.appendChild(r)});t.appendChild(body);el(target).replaceChildren(t);}
function visible(){const employee=el('report-employee').value.trim();return employee?records.filter(r=>r.employeeNumber===employee):records;}
function render(){if(!authorized)return;const rows=visible(),report=window.UsageCore.summarize(rows);el('metrics').textContent='瀏覽器訪客 '+report.visitors+'｜工作階段 '+report.sessions+'｜回訪瀏覽器 '+report.returningVisitors+'｜使用紀錄 '+report.records;table('employee-table',['employeeNumber','activeDays','logins','queries','received','returned','archived','failures','lastUsed'],['職號','使用天數','登入','查詢','收文','退文','歸檔','失敗','最近使用'],report.employees);table('daily-table',['date','views','logins','operations','failures'],['日期','頁面造訪','登入','成功公文操作','失敗'],report.daily);table('record-table',columns,titles,rows);}
function subscribe(){if(!authorized)return;if(stop)stop();records=[];render();message('讀取使用紀錄中…');const since=Timestamp.fromDate(new Date(Date.now()-Number(el('report-days').value)*86400000));stop=onSnapshot(query(collection(db,'usageRecords'),where('occurredAt','>=',since),orderBy('occurredAt','desc')),snapshot=>{if(!authorized)return;records=snapshot.docs.map(item=>{const data=item.data();return {...data,occurredAt:data.occurredAt.toDate().toISOString()}});render();message('管理者：'+auth.currentUser.email+'｜已同步 '+new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}));},()=>{clearReport();message('無法讀取報表，請確認管理權限與網路連線。');});}
function loginError(error){if(error.code==='auth/operation-not-allowed')return 'Firebase 尚未啟用 Google 登入，請在 Authentication → 登入方式啟用 Google。';if(error.code==='auth/unauthorized-domain')return '網站網域尚未獲授權，請在 Authentication → 設定 → 已授權網域加入 alexliu1975.github.io。';if(error.code==='auth/popup-blocked')return '登入視窗被阻擋，請允許此網站開啟彈出視窗。';if(error.code==='auth/popup-closed-by-user')return '登入已取消。';return 'Google 登入失敗，請稍後重試。';}
el('admin-login').onclick=async()=>{el('admin-login').disabled=true;message('等待 Google 登入…');try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(error){message(loginError(error))}finally{el('admin-login').disabled=false;}};
el('admin-logout').onclick=async()=>{clearReport();await signOut(auth);};
onAuthStateChanged(auth,async user=>{clearReport();el('admin-logout').hidden=!user;el('admin-login').hidden=!!user;if(!user){message('請登入以查看報表。');return;}message('驗證管理權限中…');try{const admin=await getDoc(doc(db,'reportAdmins',user.email));if(auth.currentUser?.uid!==user.uid)return;if(!admin.exists()||admin.data().enabled!==true)throw Error('denied');authorized=true;el('report-content').hidden=false;subscribe();}catch{if(auth.currentUser?.uid===user.uid)message('這個 Google 帳號沒有報表查看權限，請登出後改用授權管理者帳號。');}});
el('report-days').onchange=subscribe;el('report-refresh').onclick=subscribe;el('report-employee').oninput=render;
el('report-csv').onclick=()=>{if(!authorized)return;const quote=value=>'"'+String(value??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const text='\uFEFF'+[titles.map(quote).join(','),...visible().map(r=>columns.map(key=>quote(r[key])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='公文網站使用紀錄.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('pagehide',()=>{if(stop)stop();});
window.addEventListener('pageshow',event=>{if(event.persisted&&authorized)subscribe();});
